export interface MovimientoMercaderiaC {
    pro_codalm: string;           // Código de Almacén (3 caracteres)
    pro_codtid: string;           // Código de Tipo de Documento (3 caracteres)
    pro_numser: string;           // Número de Serie (15 caracteres)
    pro_numdoc: string;           // Número de Documento (15 caracteres)
    pro_codtit: string;           // Código de Tipo de Transacción (3 caracteres)
    pro_fecmov: Date;             // Fecha de Movimiento (datetime)
    pro_codper: string;           // Código de Personal (15 caracteres)
    pro_codtia: string;           // Código de Tipo de Anexo (2 caracteres)
    pro_codane: string;           // Código de Anexo (15 caracteres)
    pro_glomov: string;           // Glosa de Movimiento (150 caracteres)
    pro_almref?: string | null;   // Almacén de Referencia (50 caracteres, opcional)
    pro_serref: string;           // Serie de Referencia (15 caracteres)
    pro_numref: string;           // Número de Referencia (15 caracteres)
    pro_estmov: string;           // Estado de Movimiento (15 caracteres)
    pro_codptv: string;           // Código de Punto de Venta (3 caracteres)
    pro_modmov?: string | null;   // Modo de Movimiento (25 caracteres, opcional)
    pro_codfpa: string;           // Código de Forma de Pago (3 caracteres)
    pro_fecref?: Date | null;     // Fecha de Referencia (date, opcional)
  }