export interface MovimientoRolloC {
    pro_codtic: string;           // Código TIC (15 caracteres)
    pro_codtid: string;           // Código de Tipo de Documento (3 caracteres)
    pro_numser: string;           // Número de Serie (15 caracteres)
    pro_numdoc: string;           // Número de Documento (15 caracteres)
    pro_codtit: string;           // Código de Tipo de Transacción (3 caracteres)
    pro_fecmov: Date;             // Fecha de Movimiento (datetime)
    pro_glomov: string;           // Glosa de Movimiento (150 caracteres)
    pro_sergui: string;           // Serie de Guía (15 caracteres)
    pro_numgui: string;           // Número de Guía (15 caracteres)
    pro_serfac: string;           // Serie de Factura (15 caracteres)
    pro_numfac: string;           // Número de Factura (15 caracteres)
    pro_fecgui: Date;             // Fecha de Guía (datetime)
    pro_numref: string;           // Número de Referencia (15 caracteres)
    pro_estmov: string;           // Estado de Movimiento (15 caracteres)
    pro_codemp: string;           // Código de Empresa (2 caracteres)
    NOMBRE_FACTURA?: string | null; // Nombre de Factura (100 caracteres, opcional)
    pro_codtia?: string | null;   // Código de Tipo de Anexo (2 caracteres, opcional)
    pro_codane?: string | null;   // Código de Anexo (15 caracteres, opcional)
    pro_modmov: string;           // Modo de Movimiento (15 caracteres)
  }