import { Prisma } from "@prisma/client";

export interface ParteProduccionD {
  pro_codtic: string;           // Código TIC (15 caracteres)
  pro_codfol: string;           // Código Folio (15 caracteres)
  pro_numser: string;           // Número de Serie (15 caracteres)
  pro_numdoc: string;           // Número de Documento (15 caracteres)
  pro_itemov: Prisma.Decimal;          // Ítem de Movimiento (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_codart: string;           // Código de Artículo (15 caracteres)
  pro_nomart: string;           // Nombre de Artículo (250 caracteres)
  pro_canart: Prisma.Decimal;          // Cantidad de Artículo (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales)
  pro_numcap: Prisma.Decimal;          // Número de Capas (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales)
  pro_cancor: Prisma.Decimal;          // Cantidad de Corte (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales)
  pro_canres: Prisma.Decimal;          // Cantidad de Reserva (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales)
  pro_codori: string;           // Código de Origen (50 caracteres)
  pro_codcol: string;           // Código de Color (15 caracteres)
  pro_premet: Prisma.Decimal;          // Precio por Metro (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales)
  pro_preart: Prisma.Decimal;          // Precio de Artículo (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales)
  pro_canta1: Prisma.Decimal;          // Cantidad Talla 1 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canta2: Prisma.Decimal;          // Cantidad Talla 2 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canta3: Prisma.Decimal;          // Cantidad Talla 3 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canta4: Prisma.Decimal;          // Cantidad Talla 4 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canta5: Prisma.Decimal;          // Cantidad Talla 5 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canta6: Prisma.Decimal;          // Cantidad Talla 6 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canad1: Prisma.Decimal;          // Cantidad Adicional 1 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canad2: Prisma.Decimal;          // Cantidad Adicional 2 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_canad3: Prisma.Decimal;          // Cantidad Adicional 3 (numeric, 18 dígitos, 0 Prisma.Decimales)
  pro_terrol: string;           // Terminación de Rollo (1 carácter)
  pro_numref: string;           // Número de Referencia (15 caracteres)
  pro_hilrem: string;           // Hilo Remanente (50 caracteres)
  pro_hilcos: string;           // Hilo de Costura (50 caracteres)
  pro_grumes?: string | null;   // Grupo de Merma (10 caracteres, opcional)
  pro_coddob1?: string | null;  // Código Doble 1 (15 caracteres, opcional)
  pro_coddob2?: string | null;  // Código Doble 2 (15 caracteres, opcional)
  pro_codtiz1?: string | null;  // Código Tiza 1 (15 caracteres, opcional)
  pro_codtiz2?: string | null;  // Código Tiza 2 (15 caracteres, opcional)
  pro_codcor1?: string | null;  // Código Corrida 1 (15 caracteres, opcional)
  pro_codcor2?: string | null;  // Código Corrida 2 (15 caracteres, opcional)
  pro_codetd?: string | null;   // Código Etiqueta D (15 caracteres, opcional)
  pro_codett?: string | null;   // Código Etiqueta T (15 caracteres, opcional)
  pro_codaum?: string | null;   // Código Aumento (15 caracteres, opcional)
  pro_revmts?: Prisma.Decimal | null;  // Revisión de Metros (Prisma.Decimal, 18 dígitos, 2 Prisma.Decimales, opcional)
}